# Generated by Django 5.0 on 2024-01-18 17:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=2000)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('op1', models.CharField(max_length=500)),
                ('op2', models.CharField(max_length=500)),
                ('op3', models.CharField(max_length=500)),
                ('op4', models.CharField(max_length=500)),
                ('question_subject', models.CharField(max_length=10)),
                ('answer', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadyTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=10)),
                ('test_descripition', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_test.question')),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_test.readytest')),
            ],
        ),
        migrations.CreateModel(
            name='TestToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_done', models.BooleanField(default=False)),
                ('grade', models.FloatField(default=0)),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_test.readytest')),
            ],
        ),
    ]
